### ISSUE TITLE
'patho_ids' is empty in ConvertPhysionet.py

### ISSUE THREAD

**Issue by yjwtheonly** [paulhager/MIMIC-Clinical-Decision-Making-Dataset#1]
Thank you very much for sharing such a meaningful dataset. However, it seems that there are some bugs in ConvertPhysionet.py that need to be fixed. In ConvertPhysionet.py, from Line 130 to Line 152, 'patho_ids' is initially set to four empty lists, but then in Line 142:

https://github.com/paulhager/MIMIC-Clinical-Decision-Making-Dataset/blob/9e02802cb94a07928fbf88aa2bf94a8de3e7bedf/ConvertPhysionet.py#L142

the enumeration of patho_ids begins, which directly results in ConvertPhysionet.py generating four empty files.

**Comment by paulhager** [comment]
Hi,

Thanks for your interest in the dataset, and for finding this error. I had forgotten to upload the necessary file. There was also an error in the columns of a different file, so I recommend you redownload the dataset from physionet in a couple of days when version 1.1 has been approved. Keep an eye out, we have just submitted the adjusted dataset and it should hopefully be updated soon. I'll post here again once its online.

**Comment by paulhager** [comment]
The newest version has now been published by Physionet (https://physionet.org/content/mimic-iv-ext-cdm/1.1/) and should resolve this issue. If you have any further problems feel free to open another issue
