### ISSUE TITLE
Question of Python version

### ISSUE THREAD

**Issue by cute149q** [paulhager/MIMIC-Clinical-Decision-Making-Dataset#2]
Hi,
I am wondering which python version should be chosen for this repo. I am using 3.10 to 3.13. However, they all failed at the installment stage. Could you please provide the python version for this project? Thanks

**Comment by paulhager** [comment]
Its 3.10 as specified in the README. I just tested it again with a fresh environment and it worked without a problem

`conda create -n cdm python=3.10`
`conda activate cdm`
`pip install --no-deps -r requirements.txt`

**Comment by cute149q** [comment]
Hi,
Thanks for your fast reply. I think I found why. It should be the system issue. I am using a Mac. There are some packages not suitable for Mac. Thanks why it is not working. 
Thanks,
Shan

**Comment by paulhager** [comment]
Ah ok, sorry to hear that. If you find a setup that works feel free to open a pull request!
